### PR TITLE
PJL-2986: ADSK/PlanGrid customizations after merge with upstream repo

### PR DESCRIPTION
**Pull request by edquan**
This PR includes a merge from the upstream repo, see the latest commit for actual changes.

The commits for the previous customizations have been dropped and reworked, notable changes include:
* Debian files
  * Installation of the HyperLogLog (HLL) extension] as required by plangrid-insights.
  * Removal of volume for data as this does not get cleaned up when the container is torn down (see PlanGrid: DEVOPS-620).
* Note: Alpine files have not been updated.
* Removal of `./github/workflows/` files to prevent unnecessary GitHub CI builds for this fork.

For Postgres 13, `postgres-13-hll` is not yet available.  A `TODO` has been placed in `13/Dockerfile` to highlight this future work.

These changes will need to be force pushed to `master`.

 JIRA Tickets | 
 --------------| 
 [PJL-2986](https://jira.autodesk.com/browse/PJL-2986)|

FYI - @kneblett Has written up a [rollback plan](https://wiki.autodesk.com/display/SCFICOE/Postgres+docker+version+rollback) as part of [RELOPS-3260](https://jira.autodesk.com/browse/RELOPS-3260) in case we encounter any issued related to deploying new images.

### CODE REVIEW

**Comment by edquan** [comment]
Log of what was done to get here ...

### Merge with upstream
```
➜  postgres git:(master) ✗ git pull
Already up to date.
➜  postgres git:(master) ✗ git remote -v
origin	git@github.com:plangrid/postgres.git (fetch)
origin	git@github.com:plangrid/postgres.git (push)
➜  postgres git:(master) ✗ git remote add upstream git@github.com:docker-library/postgres.git
➜  postgres git:(master) ✗ git fetch upstream
From github.com:docker-library/postgres
 * [new branch]      master     -> upstream/master
➜  postgres git:(master) ✗ git checkout -b PJL-2986
Switched to a new branch 'PJL-2986'
➜  postgres git:(PJL-2986) ✗ git merge upstream/master
```

The following custom commits were kept in the history but reverted:
```
d df391b6 Removing the Volumes for these images [ticket: DEVOPS-620]
d 73f9e5c Updating all dockerfiles to have UTF8 default
d 4cec0e8 First attempt at a Jenkinsfile for postgres docker images
d 0465eae Fixing up the Jenkinsfile for parallel execution
d 22224d0 chg: Pulling in all the updates
d 5b943ed new: Building postgres 10 image as well
d d58f790 Add postgresql hll extension to 9.6 and 10
d 8ff9d4d add postgres11 and update old images
d b9acac9 apparently gnupg is not accessible from jenkins
```

### Custom changes
See PR description.

### Manual verification
#### Postgres 9.5
```
➜  postgres git:(PJL-2986) ✗ docker stop $(docker container ls -aq); docker container rm $(docker container ls -aq); docker image rm -f plangrid_postgres_9.5;  docker build -t plangrid_postgres_9.5 9.5/; docker run -dp 15432:5432 -e POSTGRES_PASSWORD=password123 plangrid_postgres_9.5; sleep 5; docker ps -l

<snip>

➜  postgres git:(PJL-2986) ✗ psql "postgres:password123//postgres@localhost:15432"
Expanded display is used automatically.
psql (12.3, server 9.5.23)
Type "help" for help.

postgres=# SELECT version();
                                                               version
--------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.5.23 on x86_64-pc-linux-gnu (Debian 9.5.23-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)

postgres=# CREATE EXTENSION hll;
CREATE EXTENSION
postgres=# \dx
                    List of installed extensions
  Name   | Version |   Schema   |            Description
---------+---------+------------+-----------------------------------
 hll     | 2.14    | public     | type for storing hyperloglog data
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=# \q
```

#### Postgres 9.6
```
➜  postgres git:(PJL-2986) ✗ docker stop $(docker container ls -aq); docker container rm $(docker container ls -aq); docker image rm -f plangrid_postgres_9.6;  docker build -t plangrid_postgres_9.6 9.6/; docker run -dp 15432:5432 -e POSTGRES_PASSWORD=password123 plangrid_postgres_9.6; sleep 5; docker ps -l

➜  postgres git:(PJL-2986) ✗ psql "postgres://postgres:password123@localhost:15432"
Expanded display is used automatically.
psql (12.3, server 9.6.19)
Type "help" for help.

postgres=# SELECT version();
                                                               version
--------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.19 on x86_64-pc-linux-gnu (Debian 9.6.19-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)

postgres=# CREATE EXTENSION hll;
CREATE EXTENSION
postgres=# \dx
                    List of installed extensions
  Name   | Version |   Schema   |            Description
---------+---------+------------+-----------------------------------
 hll     | 2.14    | public     | type for storing hyperloglog data
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=# \q
```

#### Postgres 10
```
➜  postgres git:(PJL-2986) ✗ docker stop $(docker container ls -aq); docker container rm $(docker container ls -aq); docker image rm -f plangrid_postgres_10;  docker build -t plangrid_postgres_10 10/; docker run -dp 15432:5432 -e POSTGRES_PASSWORD=password123 plangrid_postgres_10; sleep 5; docker ps -l


➜  postgres git:(PJL-2986) ✗ psql "postgres://postgres:password123@localhost:15432"
Expanded display is used automatically.
psql (12.3, server 10.14 (Debian 10.14-1.pgdg90+1))
Type "help" for help.

postgres=# SELECT version();
                                                              version
------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 10.14 (Debian 10.14-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)

postgres=# CREATE EXTENSION hll;
CREATE EXTENSION
postgres=# \dx
                    List of installed extensions
  Name   | Version |   Schema   |            Description
---------+---------+------------+-----------------------------------
 hll     | 2.14    | public     | type for storing hyperloglog data
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=# \q
```

#### Postgres 11
```
➜  postgres git:(PJL-2986) ✗ docker stop $(docker container ls -aq); docker container rm $(docker container ls -aq); docker image rm -f plangrid_postgres_11;  docker build -t plangrid_postgres_11 11/; docker run -dp 15432:5432 -e POSTGRES_PASSWORD=password123 plangrid_postgres_11; sleep 5; docker ps -l


➜  postgres git:(PJL-2986) ✗ psql "postgres://postgres:password123@localhost:15432"
Expanded display is used automatically.
psql (12.3, server 11.9 (Debian 11.9-1.pgdg90+1))
Type "help" for help.

postgres=# SELECT version();
                                                             version
----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.9 (Debian 11.9-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)

postgres=# CREATE EXTENSION hll;
CREATE EXTENSION
postgres=# \dx
                    List of installed extensions
  Name   | Version |   Schema   |            Description
---------+---------+------------+-----------------------------------
 hll     | 2.14    | public     | type for storing hyperloglog data
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=# \q
```

#### Postgres 12
```

➜  postgres git:(PJL-2986) ✗ docker stop $(docker container ls -aq); docker container rm $(docker container ls -aq); docker image rm -f plangrid_postgres_12;  docker build -t plangrid_postgres_12 12/; docker run -dp 15432:5432 -e POSTGRES_PASSWORD=password123 plangrid_postgres_12; sleep 5; docker ps -l

➜  postgres git:(PJL-2986) ✗ psql "postgres://postgres:password123@localhost:15432"
Expanded display is used automatically.
psql (12.3, server 12.4 (Debian 12.4-1.pgdg100+1))
Type "help" for help.

postgres=# SELECT version();
                                                     version
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

postgres=# CREATE EXTENSION hll;
CREATE EXTENSION
postgres=# \dx
                    List of installed extensions
  Name   | Version |   Schema   |            Description
---------+---------+------------+-----------------------------------
 hll     | 2.14    | public     | type for storing hyperloglog data
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=# \q
```

#### Postgres 13
Take note that the `hll` extension could not be created, see PR description.
```
➜  postgres git:(PJL-2986) ✗ docker stop $(docker container ls -aq); docker container rm $(docker container ls -aq); docker image rm -f plangrid_postgres_13;  docker build -t plangrid_postgres_13 13/; docker run -dp 15432:5432 -e POSTGRES_PASSWORD=password123 plangrid_postgres_13; sleep 5; docker ps -l


➜  postgres git:(PJL-2986) ✗ psql "postgres://postgres:password123@localhost:15432"
Expanded display is used automatically.
psql (12.3, server 13.0 (Debian 13.0-1.pgdg100+1))
WARNING: psql major version 12, server major version 13.
         Some psql features might not work.
Type "help" for help.

postgres=# SELECT version();
                                                     version
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

postgres=# CREATE EXTENSION hll;
ERROR:  could not open extension control file "/usr/share/postgresql/13/extension/hll.control": No such file or directory
postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=# \q
```

**Comment by edquan** [comment]
The force deb builds are failing here:
* https://github.com/plangrid/postgres/pull/7/checks?check_run_id=1221824583

for:
* 12.4 (force deb build)
* 11.9 (force deb build)
* 10.14 (force deb build)
* 9.6.19 (force deb build)
* 9.5.23 (force deb build)

but not:
* 13.0 (force deb build)

This is specifically because it cannot locate the `postgresql-XX-hll` packages.  For 13.0, `postgresql-13-hll` has been intentionally removed as it is not yet available (see PR description).

Not sure how to get around this, any suggestions would be greatly appreciated!

It might also be good to see if anyone still needs this extension and whether or not it will be available in RDS for future use.
Update: [HLL is available in RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html) and the Insights service has it installed/created.

Update: `..github/workflows/` files were removed, so this is no longer an issue.

**Comment by goosemo** [comment]
Is this all to try and get a postgres 12 docker image available for SBS?  Perhaps there is a simpler way to manage this that wouldn't pull in a much of this at the same time.

**Review by paydro — APPROVED** [review]
LGTM - from a database configuration perspective. That said, I can't guide you on whether this is the correct path and will rely on Morgan :)

**Comment by edquan** [comment]
> Is this all to try and get a postgres 12 docker image available for SBS? Perhaps there is a simpler way to manage this that wouldn't pull in a much of this at the same time.

@goosemo: Yes, the intent is to get a Postgres 12 docker image for SBS.  PADD was recently upgraded to RDS Postgres 12 to allow a feature called "declarative partitioning" to be used so we need this image available for our builds.

We _could_ just try to clone the existing PlanGrid Postgres build steps from a prior release and hope that the old build practices work as-is but that introduces risk as well.  Instead I chose to rebase this repo with the upstream official Postgres docker image and apply and document the necessary changes up to this point.  The deviation exists in the latest commit:
* https://github.com/plangrid/postgres/pull/7/commits/fe9bd150d6669123039a7ae0a8ce9ccdc6ee975d

Going forward it will be much easier to manage future releases as we are in sync with the upstream repo.  It took me a bit of time to comb through our history to understand what/why things were changed, something that future maintainers would need to revisit.  The risk is that something has been missed and an existing user of the past images may encounter an issue.  However, rebasing moves us forward rather than living in the past.

An alternative would be for us to take the changes specifically for Postgres 12 and 13 and commit those changes (without doing a rebase).  This would limit our scope to those particular images and not impact the existing ones.  However, we will continue to diverge from the upstream repo which makes it more difficult for future maintainers to update or pull in new releases.

Another alternative would be to take a baby step by using the latter of the two approaches, such that PADD is unblocked.  Then after that has been proven to work, revisit this with the original solution of rebasing (I can keep these changes on a branch so it's easier to pick-up where we left off).  This is my recommended approach.

Thoughts?

Updated: Link to git commit hash since a force push was done after cleaning up some files.

**Comment by edquan** [comment]
After pushing a branch to origin which matches the `master` branch (commit: [`43d737b`](https://github.com/plangrid/postgres/commit/43d737b1cf0439f9087b6bd9ecfcfa389991a254)), it appears that the as-is build is failing for at least Postgres 9.5, 10 and 11:
* https://jenkins.planfront.net/blue/organizations/jenkins/plangrid%2Fpostgres/detail/PJL-2986_postgres_12/1/pipeline

it looks like the original push to the `master` branch failed as well:
* https://jenkins.planfront.net/blue/organizations/jenkins/plangrid%2Fpostgres/activity

The original plan of rebasing with the upstream repo and applying the PlanGrid changes looks like the way we should be approaching this.  A close second would be to adopt only the Postgres 12 docker files and change the Jenkins file to only push the Postgres 12 image and not any of the others.

**Comment by edquan** [comment]
Local images were created and tested using a local version of SBS against:
* PADD with Postgres 9.5, 9.6, 10, 11, 12 and 13.
* Insights (which requires the HLL extension) with Postgres 9.5, 9.6, 10, 11, 12 (13 was not tested since the HLL extension is not yet available).

Other services such as Cacahuete, Customer API, Shredder and Scribbler were tested but encountered other unrelated build issues.

```
# Remove PlanGrid Postgres images ..
(padd) ➜  padd git:(PJL-2986) ✗ docker rm <plangrid_postgres_images_ids>

# Run SBS build against PADD for each version of PlanGrid Postgres
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='95' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='96' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='10' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='11' /opt/plangrid/build-tools/bin/build

# Remove PlanGrid Postgres images ...
(padd) ➜  padd git:(PJL-2986) ✗ docker rm <plangrid_postgres_images_ids>

# Build local PlanGrid Postgres images
➜  postgres git:(PJL-2986) ✗ docker build -t '723151894364.dkr.ecr.us-east-1.amazonaws.com/postgres95' 95/
➜  postgres git:(PJL-2986) ✗ docker build -t '723151894364.dkr.ecr.us-east-1.amazonaws.com/postgres96' 96/
➜  postgres git:(PJL-2986) ✗ docker build -t '723151894364.dkr.ecr.us-east-1.amazonaws.com/postgres10' 10/
➜  postgres git:(PJL-2986) ✗ docker build -t '723151894364.dkr.ecr.us-east-1.amazonaws.com/postgres11' 11/
➜  postgres git:(PJL-2986) ✗ docker build -t '723151894364.dkr.ecr.us-east-1.amazonaws.com/postgres12' 12/
➜  postgres git:(PJL-2986) ✗ docker build -t '723151894364.dkr.ecr.us-east-1.amazonaws.com/postgres13' 13/

# Run SBS build against PADD for each version of PlanGrid Postgres
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='95' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='96' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='10' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='11' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='12' /opt/plangrid/build-tools/bin/build
(padd) ➜  padd git:(PJL-2986) ✗ DEFAULT_NOSETESTS="nosetests-3.4" DEFAULT_PYTHON='python3' DEFAULT_PIP='pip3' POSTGRES_VERSION='13' /opt/plangrid/build-tools/bin/build

# Repeat for Insights or other repos ...
```

**Review by goosemo — APPROVED** [review]
After talking through these changes and making both the rollout and rollback plan, these are good to go.

**Comment by edquan** [comment]
Note: This PR has been updated to make use of a merge rather than a rebase to preserve the history and make this PR fast-forward friendly.

**Pull request merged**
